CREATE TABLE IF NOT EXISTS USER (
  ID BIGSERIAL PRIMARY KEY,
  EMAIL VARCHAR(45) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(45) NOT NULL,
  LAST_NAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  ROLE_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLE (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRESENCE (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  DATE TIMESTAMP NOT NULL,
  CONSTRAINT FK_PRESENCE_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

INSERT INTO ROLE (ID, NAME) VALUES (1, 'DOZENT');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'STUDENT');

INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, ENABLED, ROLE_ID) VALUES ('spiess.andi@web.de', 'Andreas', 'Spieß', '$2a$10$FE5bHSpWg8H53A0O1aQ1/OyN87vv96XA5dqKfA4cAw9EmbKGwLRB2','true', 1)